on:
  push:
    branches:
      - main
name: 🚀 Deploy test website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.sintoniza-t.pt
          username: sintoniz
          password: K.2tZGu8eZ*8a9
          server-dir: api.sintoniza-t.pt/production/
          